# Experimental per-key/reactive RGB support (requires Hanks ZMK fork on this branch)
CONFIG_ZMK_LED_MAP=y
CONFIG_ZMK_LED_MAP_PER_KEY_BRT_MAX=10
CONFIG_ZMK_LED_MAP_INDICATOR_BRT_MAX=5
CONFIG_ZMK_LED_MAP_EFF_START=4
CONFIG_ZMK_LED_MAP_ON_START=y
CONFIG_ZMK_HID_INDICATORS=y
CONFIG_ZMK_BATTERY_REPORTING=y
